### ISSUE TITLE
Can we have an RSS feed for these?

### ISSUE THREAD

**Issue by elvis-sik** [mikeckennedy/talk-python-transcripts#166]
Thank you for the podcast and for the transcripts! I'm moving away from getting information through audio at the moment, and would love to be able to continue "listening" to the conversations.

Could we maybe have an RSS feed for these?

**Comment by mikeckennedy** [comment]
Hi Elvis. It's a good idea but I don't have time to add the feature at the moment. For now, you'd probably be best off just subscribing to notifications for this repo by "watching" it. I'll keep it in mind as a feature of the site

**Comment by elvis-sik** [comment]
Thank you!
