### ISSUE TITLE
looking for the transcript for ep 263 - SEO for developers

### ISSUE THREAD

**Issue by simkimsia** [mikeckennedy/talk-python-transcripts#178]
Not urgent

I suppose you will upload that in June or something. Just putting this here to remind myself to look out for it when it's ready.

Thank you 🙏 , Michael

**Comment by mikeckennedy** [comment]
Hi @simkimsia Thanks for bringing this up. The company that was automatically doing these stopped doing that type of work. I have someone working on transcripts for me, but they are fully busy on course transcripts which are super important. Plus, these are like $100 / episode. 

Honestly, I haven't decided whether to keep doing them...

Best,
Michael

**Comment by simkimsia** [comment]
oh i see. then i will get this transcribed and send you? By the way, may not be as good a transcript as your previous ones.

**Comment by mikeckennedy** [comment]
Hi,

Sure, if you wanted to make transcripts, I would definitely accept them. If
they could match the format of what's in the github repo, then they could
even be imported and searched by the site which would be great.

Best,
Michael
