### ISSUE TITLE
time display  on talkpython.fm seems wrong

### ISSUE THREAD

**Issue by sunyiwei24601** [mikeckennedy/talk-python-transcripts#180]
I am listening to Episode 246 on talkpython.fm with transcripts and I find that the any sentences later than 23:48 minutes displays wrongly. They all stay at 23:48 like following:
![image](https://user-images.githubusercontent.com/32425755/83588030-7f34f380-a51e-11ea-8119-59cefb42d4f9.png)
On other Episode I also find similar problems(Episode 251):
![image](https://user-images.githubusercontent.com/32425755/83588077-94118700-a51e-11ea-8de3-0e882bfca5d9.png)
So I came to the source file on github and find it correctly label the time.So is there something on the Website Display?

**Comment by mikeckennedy** [comment]
Hi,

Sorry about that. The service I'm using for generating these is having
issues. They are looking into it.

Best,
Michael
