### ISSUE TITLE
Transcripts in markdown format

### ISSUE THREAD

**Issue by dfurtado** [mikeckennedy/talk-python-transcripts#2]
Hi Michael,

Have you consider having the episode transcripts in markdown? I think it would be very helpful to read it on GitHub. 
If you think it's a good idea I would be more than happy in helping out.

**Comment by mikeckennedy** [comment]
Hi Dfurtado,

Thanks for the idea. I have code that parses these into an in-memory model for this page for search and such:

https://talkpython.fm/episodes/transcript/51/sigopt-optimizing-everything-with-python

I could use it to generate a markdown variant easy enough. What did you have in mind for the output format?

**Comment by leobiscassi** [comment]
Hi folks,
I would be happy in help in this process. The transcripts are awesome way to study english (I'm from Brazil), listening about one of my favorite programming languages.
