### ISSUE TITLE
How did you transcribe the audio?

### ISSUE THREAD

**Issue by wengertj** [mikeckennedy/talk-python-transcripts#3]
Hi Michael,

I was wondering how you managed to transcribe such a large number of audio files? "Manually"? (if so then my respect for you just has grown to infinity...) or have you used some speech-recognition-API? Just curious because I have to transcribe a number of interviews myself and was wondering if there was any sort of speech-recognition-service that could help me save some time.

Thanks for the great podcast and the additional work for the transcripts :+1: 
Jo

**Comment by mikeckennedy** [comment]
Hi there,

Thanks so much. I wish I had the time and energy to do these myself. I actually hired a woman who does this kind of thing part-time and will spend a few hours a week making transcripts for my show. :)
